### ISSUE TITLE
Unable to access local farm when testing resource (running SharePoint commands as a specific user)

### ISSUE THREAD

**Issue by BrianTJackett** [wulfland/xSharePointAdministration#1]
I am attempting to test out the xSite configuration but when I run the sample configuration I get an error about not being able to access the local farm.  I assume this is related to running as "nt authority\system" rather than an account that is a farm administrator.  How you found a workaround for this or do I have something misconfigured?

**Comment by wulfland** [comment]
I tested it on a development machines and in production environments and it works everywhere. Did you run the configuration in push or pull mode?  My _winmgmt_ Service also runs as "Local System" on all machines. Can you check, that you System account is in the wss_wpg group? 

If you want to use the xList resource, then you have to create a policy for your web application that allows the System account access.

I just noted one more this: my SharePoint administration service runs on all the machines as local system. Can you check if this is also the case in you environment?

**Comment by BrianTJackett** [comment]
I ran my configuration in push mode on a dev machine.  I did not add Local System to the wss_wpg.  I will try that and let you know how it turns out.

P.S. Wahid from Microsoft is one of my coworkers and I am on a project with him to look into PowerShell DSC for SharePoint.  He told me he reached out to you regarding this project.  Hopefully we can help each other expand the coverage of this.  I like what you have created so far.

**Comment by wulfland** [comment]
Have you tried it yet?

**Comment by BrianTJackett** [comment]
Sorry I have not yet gotten a chance.  My customer decided not to go down the route of DSC for SharePoint due to project timelines.  I hadn't gotten back to testing on this.  Based on the feedback from the internal project it sounds like the xPDT resource may be a way to accomplish the passing of credentials in a more structured way.

Date: Thu, 5 Feb 2015 07:42:24 -0800
